### ISSUE TITLE
Enable Mentions

### ISSUE THREAD

**Issue by schrismartin** [schrismartin/jarvis-vapor#4]
## Description
Jarvis must be able to parse mentions as they come in, and must be able to mention others in outbound messages.

## Purpose
This will allow for features in including the `harass`, `broadcast`, and other features that require a `user_id` in order to identify and react to a non-calling user.

## Todo
- [x] Implement automatic parsing of inbound mentions and user creation.
- [x] Implement smart means of constructing message queries that allow for users to be mentioned.
- [x] Determine JSON schema for sending messages with mentions.

## Example Usage
_N/A_
